USE [master]
GO

/****** Object:  Database [Alpha_Music]    Script Date: 4/30/2019 10:02:25 PM ******/
CREATE DATABASE [Alpha_Music]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Alpha_Music', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Alpha_Music.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Alpha_Music_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Alpha_Music_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Alpha_Music] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Alpha_Music].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Alpha_Music] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Alpha_Music] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Alpha_Music] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Alpha_Music] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Alpha_Music] SET ARITHABORT OFF 
GO

ALTER DATABASE [Alpha_Music] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Alpha_Music] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Alpha_Music] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Alpha_Music] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Alpha_Music] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Alpha_Music] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Alpha_Music] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Alpha_Music] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Alpha_Music] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Alpha_Music] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Alpha_Music] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Alpha_Music] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Alpha_Music] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Alpha_Music] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Alpha_Music] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Alpha_Music] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Alpha_Music] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Alpha_Music] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Alpha_Music] SET  MULTI_USER 
GO

ALTER DATABASE [Alpha_Music] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Alpha_Music] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Alpha_Music] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Alpha_Music] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Alpha_Music] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Alpha_Music] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Alpha_Music] SET  READ_WRITE 
GO

